version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./analysis_results:/app/analysis_results
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: python src/main.py 